const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Text,
		C3.Plugins.sliderbar,
		C3.Plugins.Sprite,
		C3.Plugins.Mouse,
		C3.Behaviors.Flash,
		C3.Behaviors.EightDir,
		C3.Behaviors.bound,
		C3.Behaviors.scrollto,
		C3.Behaviors.Platform,
		C3.Behaviors.Fade,
		C3.Plugins.video,
		C3.Behaviors.solid,
		C3.Behaviors.Tween,
		C3.Behaviors.MoveTo,
		C3.Plugins.Audio,
		C3.Behaviors.DragnDrop,
		C3.Plugins.Button,
		C3.Behaviors.Car,
		C3.Plugins.Keyboard,
		C3.Plugins.Browser,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Behaviors.MoveTo.Acts.MoveToPosition,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Browser.Acts.GoToURLWindow,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.System.Acts.ResetEventVar,
		C3.Plugins.Mouse.Cnds.OnClick,
		C3.Plugins.Text.Acts.TypewriterText,
		C3.Plugins.Text.Acts.TypewriterFinish,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.video.Acts.SetVisible,
		C3.Plugins.video.Acts.SetSource2,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Audio.Acts.SetPaused,
		C3.Plugins.sliderbar.Acts.SetWidth,
		C3.Plugins.video.Cnds.IsVisible,
		C3.Plugins.sliderbar.Acts.SetMaximum,
		C3.Plugins.video.Exps.Duration,
		C3.Plugins.sliderbar.Acts.SetVisible,
		C3.Plugins.video.Cnds.IsPlaying,
		C3.Plugins.sliderbar.Acts.SetValue,
		C3.Plugins.video.Exps.PlaybackTime,
		C3.Plugins.sliderbar.Cnds.OnChanging,
		C3.Plugins.video.Acts.Play,
		C3.Plugins.sliderbar.Acts.SetInstanceVar,
		C3.Plugins.sliderbar.Exps.Value,
		C3.Plugins.video.Acts.SetPlaybackTime,
		C3.Plugins.video.Cnds.HasEnded,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Text.Acts.SetPos,
		C3.Plugins.Mouse.Acts.SetCursor,
		C3.Plugins.video.Acts.Destroy,
		C3.Plugins.Sprite.Acts.RotateClockwise,
		C3.Behaviors.DragnDrop.Cnds.OnDrop,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Keyboard.Cnds.OnKeyReleased,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Behaviors.Fade.Acts.SetFadeInTime,
		C3.Behaviors.Fade.Acts.StartFade,
		C3.Plugins.Mouse.Cnds.OnAnyClick,
		C3.Behaviors.EightDir.Acts.SetEnabled,
		C3.Behaviors.Car.Acts.SimulateControl,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Cnds.IsBetweenAngles,
		C3.Behaviors.solid.Acts.SetEnabled,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.SetCollisions
	];
};
self.C3_JsPropNameTable = [
	{Variable1: 0},
	{U143互動數量: 0},
	{影片time: 0},
	{影片進度條: 0},
	{影片進度條2: 0},
	{影片進度條3: 0},
	{Text1: 0},
	{Text2: 0},
	{Sprite: 0},
	{滑鼠: 0},
	{Sprite2: 0},
	{變量1: 0},
	{閃爍: 0},
	{Text: 0},
	{U1: 0},
	{r1: 0},
	{Sprite6: 0},
	{Sprite7: 0},
	{Sprite8: 0},
	{Sprite9: 0},
	{Sprite10: 0},
	{Sprite11: 0},
	{about: 0},
	{x1: 0},
	{r2: 0},
	{r3: 0},
	{U2: 0},
	{U3: 0},
	{Sprite21: 0},
	{"8方向": 0},
	{邊界約束: 0},
	{視野跟隨: 0},
	{平台: 0},
	{boy: 0},
	{淡入淡出: 0},
	{Sprite3: 0},
	{Video: 0},
	{contents: 0},
	{bc1: 0},
	{bc2: 0},
	{Sprite25: 0},
	{實體: 0},
	{Sprite26: 0},
	{box: 0},
	{vendor: 0},
	{motorcycle: 0},
	{dialogBox: 0},
	{Text3: 0},
	{hinder1: 0},
	{補間動畫: 0},
	{移動到: 0},
	{motor: 0},
	{car1: 0},
	{car2: 0},
	{car3: 0},
	{Text4: 0},
	{skip2: 0},
	{hinder2: 0},
	{Sprite29: 0},
	{dialogBox2: 0},
	{Text5: 0},
	{Text6: 0},
	{know1: 0},
	{x2: 0},
	{home: 0},
	{settings: 0},
	{stop: 0},
	{setting2: 0},
	{x3: 0},
	{bc3: 0},
	{bc4: 0},
	{Sprite13: 0},
	{dialogBox3: 0},
	{Text7: 0},
	{Text8: 0},
	{know2: 0},
	{x4: 0},
	{Sprite23: 0},
	{dialogBox4: 0},
	{Text9: 0},
	{Text10: 0},
	{Text11: 0},
	{更: 0},
	{未命名的作品: 0},
	{未命名的作品2: 0},
	{未命名的作品3: 0},
	{未命名的作品4: 0},
	{未命名的作品5: 0},
	{更2: 0},
	{b2: 0},
	{Sprite24: 0},
	{go1: 0},
	{音頻: 0},
	{on: 0},
	{cloud2: 0},
	{cloud1: 0},
	{go4: 0},
	{go3: 0},
	{go2: 0},
	{plant: 0},
	{know4: 0},
	{x5: 0},
	{know3: 0},
	{Sprite28: 0},
	{Sprite30: 0},
	{end: 0},
	{road3: 0},
	{Sprite15: 0},
	{road1: 0},
	{police: 0},
	{man: 0},
	{people1: 0},
	{people2: 0},
	{settingword: 0},
	{Sprite5: 0},
	{settingword2: 0},
	{settingword3: 0},
	{settingword4: 0},
	{滑動條: 0},
	{Sprite14: 0},
	{back: 0},
	{aa: 0},
	{ab: 0},
	{back2: 0},
	{Sprite27: 0},
	{Sprite31: 0},
	{Sprite32: 0},
	{Sprite33: 0},
	{"13text1": 0},
	{start: 0},
	{Sprite35: 0},
	{"13text2": 0},
	{p1: 0},
	{Sprite36: 0},
	{Sprite37: 0},
	{q1: 0},
	{o: 0},
	{o1: 0},
	{n1: 0},
	{texto: 0},
	{Text14: 0},
	{textn: 0},
	{Sprite40: 0},
	{x6: 0},
	{a1: 0},
	{Text16: 0},
	{c: 0},
	{moneyword: 0},
	{n2: 0},
	{o2: 0},
	{p2: 0},
	{Sprite34: 0},
	{Sprite38: 0},
	{boyangry: 0},
	{boynogood: 0},
	{friendwow: 0},
	{friendteach3: 0},
	{friendteach: 0},
	{highway: 0},
	{railway: 0},
	{LightRail: 0},
	{boydoubt: 0},
	{boycry: 0},
	{x7: 0},
	{angry: 0},
	{Sprite39: 0},
	{boyexbassred: 0},
	{Sprite42: 0},
	{aunt: 0},
	{Sprite41: 0},
	{c1: 0},
	{c2: 0},
	{Text12: 0},
	{Text13: 0},
	{friendteach2: 0},
	{bc: 0},
	{gb: 0},
	{IsCorrectlyPlaced: 0},
	{拖放: 0},
	{mc2: 0},
	{mc1: 0},
	{stone: 0},
	{bc5: 0},
	{IsCorrectlyPlaced2: 0},
	{Umbrella: 0},
	{Sprite45: 0},
	{Text15: 0},
	{按鈕: 0},
	{Text17: 0},
	{Sprite46: 0},
	{start2: 0},
	{Car: 0},
	{bluecar: 0},
	{鍵盤: 0},
	{WORD: 0},
	{Sprite48: 0},
	{Sprite49: 0},
	{car: 0},
	{light: 0},
	{gutterCover: 0},
	{qa: 0},
	{Sprite50: 0},
	{Text18: 0},
	{Text19: 0},
	{Sprite22: 0},
	{Umbrella2: 0},
	{bc6: 0},
	{Sprite44: 0},
	{IsCorrectlyPlaced3: 0},
	{chair1: 0},
	{mc4: 0},
	{sc: 0},
	{video2: 0},
	{skip: 0},
	{ook: 0},
	{settingword5: 0},
	{settingword6: 0},
	{settingword7: 0},
	{moneyfly: 0},
	{Sprite4: 0},
	{Sprite16: 0},
	{skip3: 0},
	{Sprite17: 0},
	{b3: 0},
	{b4: 0},
	{block1: 0},
	{dialogBox5: 0},
	{Text20: 0},
	{next: 0},
	{Sprite19: 0},
	{last: 0},
	{next2: 0},
	{Sprite43: 0},
	{Sprite51: 0},
	{back3: 0},
	{again: 0},
	{next3: 0},
	{A11: 0},
	{A22: 0},
	{A33: 0},
	{A44: 0},
	{A55: 0},
	{B11: 0},
	{B22: 0},
	{B33: 0},
	{B44: 0},
	{B55: 0},
	{C11: 0},
	{C22: 0},
	{C33: 0},
	{C44: 0},
	{C55: 0},
	{D11: 0},
	{D22: 0},
	{D33: 0},
	{D44: 0},
	{D55: 0},
	{E11: 0},
	{E22: 0},
	{E33: 0},
	{E44: 0},
	{E55: 0},
	{r4: 0},
	{r41: 0},
	{r5: 0},
	{r51: 0},
	{r6: 0},
	{r61: 0},
	{r7: 0},
	{r71: 0},
	{girl1: 0},
	{girl2: 0},
	{Text21: 0},
	{girl3: 0},
	{vedio21: 0},
	{x8: 0},
	{preservation1: 0},
	{preservation2: 0},
	{vedio22: 0},
	{x9: 0},
	{vedio23: 0},
	{back5: 0},
	{vedio24: 0},
	{x10: 0},
	{Text22: 0},
	{Text23: 0},
	{giel4: 0},
	{sc1: 0},
	{bc8: 0},
	{vedio25: 0},
	{x11: 0},
	{Text24: 0},
	{bc7: 0},
	{Solid: 0},
	{stopline1: 0},
	{Sprite18: 0},
	{Text25: 0},
	{talk2: 0},
	{talk3: 0},
	{talk4: 0},
	{map: 0},
	{stopline2: 0},
	{stopline3: 0},
	{stopline4: 0},
	{x12: 0},
	{back6: 0},
	{start5: 0},
	{bc10: 0},
	{U11: 0},
	{U12: 0},
	{U14: 0},
	{U15: 0},
	{skip55: 0},
	{Text26: 0},
	{ed: 0},
	{yellow: 0},
	{Sprite20: 0},
	{U224: 0},
	{U31: 0},
	{U32: 0},
	{map2: 0},
	{music2: 0},
	{moal: 0},
	{right2: 0},
	{left2: 0},
	{right3: 0},
	{left3: 0},
	{settingmoal: 0},
	{x13: 0},
	{setting3: 0},
	{aa1: 0},
	{aa2: 0},
	{sale: 0},
	{piece1: 0},
	{piece2: 0},
	{piece3: 0},
	{piece4: 0},
	{lamp: 0},
	{chair2: 0},
	{chair3: 0},
	{chair4: 0},
	{chair5: 0},
	{aa3: 0},
	{bc12: 0},
	{IsCorrectlyPlaced4: 0},
	{carrrrr1: 0},
	{carrrrrr2: 0},
	{gutterCover2: 0},
	{glass: 0},
	{aa4: 0},
	{U2setting: 0},
	{ok1: 0},
	{settingmeal2: 0},
	{Obstruct1: 0},
	{Obstruct2: 0},
	{Obstruct3: 0},
	{Obstruct4: 0},
	{Obstruct5: 0},
	{bc13: 0},
	{IsCorrectlyPlaced5: 0},
	{car5: 0},
	{mc5: 0},
	{bc14: 0},
	{IsCorrectlyPlaced6: 0},
	{people: 0},
	{venders: 0},
	{plant2: 0},
	{wash: 0},
	{play: 0},
	{x14: 0},
	{bc15: 0},
	{play2: 0},
	{x15: 0},
	{變數1: 0},
	{rr1: 0},
	{rr2: 0},
	{rr3: 0},
	{rr4: 0},
	{rr11: 0},
	{rr44: 0},
	{rr22: 0},
	{rr33: 0},
	{u25sertting: 0},
	{circle: 0},
	{line1: 0},
	{line2: 0},
	{line3: 0},
	{line4: 0},
	{circle2: 0},
	{line6: 0},
	{line7: 0},
	{line8: 0},
	{line9: 0},
	{line10: 0},
	{line11: 0},
	{line12: 0},
	{line13: 0},
	{line14: 0},
	{line16: 0},
	{line17: 0},
	{line18: 0},
	{line19: 0},
	{line20: 0},
	{line21: 0},
	{line22: 0},
	{車: 0},
	{redcar: 0},
	{aa5: 0},
	{aa6: 0},
	{next5: 0},
	{next6: 0},
	{U30: 0},
	{U40: 0},
	{U41: 0},
	{Text27: 0},
	{boyknow: 0},
	{Text28: 0},
	{Sprite12: 0},
	{com: 0},
	{read: 0},
	{fb1: 0},
	{car01: 0},
	{car001: 0},
	{Sprite52: 0},
	{Sprite53: 0},
	{Sprite54: 0},
	{Sprite55: 0},
	{Browser: 0},
	{fb0: 0},
	{fb2: 0},
	{Sprite47: 0},
	{fb3: 0},
	{Sprite56: 0},
	{continue: 0},
	{Sprite57: 0},
	{Sprite58: 0},
	{Sprite59: 0},
	{Sprite60: 0},
	{gooo: 0},
	{menu是否觸碰: 0},
	{story6: 0},
	{story2: 0},
	{story3: 0},
	{story4: 0},
	{Rightmeet: 0},
	{ps: 0},
	{musiccc: 0},
	{go: 0},
	{story5: 0},
	{story7: 0},
	{story8: 0},
	{story9: 0},
	{story10: 0},
	{story11: 0},
	{story12: 0},
	{story13: 0},
	{CurrentMission3: 0},
	{go5: 0},
	{go6: 0},
	{CurrentMission: 0},
	{set: 0},
	{CurrentMission2: 0}
];

self.InstanceType = {
	U143互動數量: class extends self.ITextInstance {},
	影片進度條: class extends self.ISliderBarInstance {},
	影片進度條2: class extends self.ISliderBarInstance {},
	影片進度條3: class extends self.ISliderBarInstance {},
	Sprite: class extends self.ISpriteInstance {},
	滑鼠: class extends self.IInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	U1: class extends self.ISpriteInstance {},
	r1: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	about: class extends self.ISpriteInstance {},
	x1: class extends self.ISpriteInstance {},
	r2: class extends self.ISpriteInstance {},
	r3: class extends self.ISpriteInstance {},
	U2: class extends self.ISpriteInstance {},
	U3: class extends self.ISpriteInstance {},
	Sprite21: class extends self.ISpriteInstance {},
	boy: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Video: class extends self.IWorldInstance {},
	contents: class extends self.ITextInstance {},
	bc1: class extends self.ISpriteInstance {},
	bc2: class extends self.ISpriteInstance {},
	Sprite25: class extends self.ISpriteInstance {},
	Sprite26: class extends self.ISpriteInstance {},
	box: class extends self.ISpriteInstance {},
	vendor: class extends self.ISpriteInstance {},
	motorcycle: class extends self.ISpriteInstance {},
	dialogBox: class extends self.ISpriteInstance {},
	Text3: class extends self.ITextInstance {},
	hinder1: class extends self.ISpriteInstance {},
	motor: class extends self.ISpriteInstance {},
	car1: class extends self.ISpriteInstance {},
	car2: class extends self.ISpriteInstance {},
	car3: class extends self.ISpriteInstance {},
	Text4: class extends self.ITextInstance {},
	skip2: class extends self.ITextInstance {},
	hinder2: class extends self.ISpriteInstance {},
	Sprite29: class extends self.ISpriteInstance {},
	dialogBox2: class extends self.ISpriteInstance {},
	Text5: class extends self.ITextInstance {},
	Text6: class extends self.ITextInstance {},
	know1: class extends self.ISpriteInstance {},
	x2: class extends self.ISpriteInstance {},
	home: class extends self.ISpriteInstance {},
	settings: class extends self.ISpriteInstance {},
	stop: class extends self.ISpriteInstance {},
	setting2: class extends self.ISpriteInstance {},
	x3: class extends self.ISpriteInstance {},
	bc3: class extends self.ISpriteInstance {},
	bc4: class extends self.ISpriteInstance {},
	Sprite13: class extends self.ISpriteInstance {},
	dialogBox3: class extends self.ISpriteInstance {},
	Text7: class extends self.ITextInstance {},
	Text8: class extends self.ITextInstance {},
	know2: class extends self.ISpriteInstance {},
	x4: class extends self.ISpriteInstance {},
	Sprite23: class extends self.ISpriteInstance {},
	dialogBox4: class extends self.ISpriteInstance {},
	Text9: class extends self.ITextInstance {},
	Text10: class extends self.ITextInstance {},
	Text11: class extends self.ITextInstance {},
	更: class extends self.ISpriteInstance {},
	未命名的作品: class extends self.ISpriteInstance {},
	未命名的作品2: class extends self.ISpriteInstance {},
	未命名的作品3: class extends self.ISpriteInstance {},
	未命名的作品4: class extends self.ISpriteInstance {},
	未命名的作品5: class extends self.ISpriteInstance {},
	更2: class extends self.ISpriteInstance {},
	b2: class extends self.ISpriteInstance {},
	Sprite24: class extends self.ISpriteInstance {},
	go1: class extends self.ISpriteInstance {},
	音頻: class extends self.IInstance {},
	on: class extends self.ISpriteInstance {},
	cloud2: class extends self.ISpriteInstance {},
	cloud1: class extends self.ISpriteInstance {},
	go4: class extends self.ISpriteInstance {},
	go3: class extends self.ISpriteInstance {},
	go2: class extends self.ISpriteInstance {},
	plant: class extends self.ISpriteInstance {},
	know4: class extends self.ISpriteInstance {},
	x5: class extends self.ISpriteInstance {},
	know3: class extends self.ISpriteInstance {},
	Sprite28: class extends self.ISpriteInstance {},
	Sprite30: class extends self.ISpriteInstance {},
	end: class extends self.ISpriteInstance {},
	road3: class extends self.ISpriteInstance {},
	Sprite15: class extends self.ISpriteInstance {},
	road1: class extends self.ISpriteInstance {},
	police: class extends self.ISpriteInstance {},
	man: class extends self.ISpriteInstance {},
	people1: class extends self.ISpriteInstance {},
	people2: class extends self.ISpriteInstance {},
	settingword: class extends self.ITextInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	settingword2: class extends self.ITextInstance {},
	settingword3: class extends self.ITextInstance {},
	settingword4: class extends self.ITextInstance {},
	滑動條: class extends self.ISliderBarInstance {},
	Sprite14: class extends self.ISpriteInstance {},
	back: class extends self.ISpriteInstance {},
	aa: class extends self.ITextInstance {},
	ab: class extends self.ITextInstance {},
	back2: class extends self.ISpriteInstance {},
	Sprite27: class extends self.ISpriteInstance {},
	Sprite31: class extends self.ISpriteInstance {},
	Sprite32: class extends self.ISpriteInstance {},
	Sprite33: class extends self.ISpriteInstance {},
	_13text1: class extends self.ITextInstance {},
	Text2: class extends self.ITextInstance {},
	start: class extends self.ISpriteInstance {},
	Sprite35: class extends self.ISpriteInstance {},
	_13text2: class extends self.ITextInstance {},
	p1: class extends self.ISpriteInstance {},
	Sprite36: class extends self.ISpriteInstance {},
	Sprite37: class extends self.ISpriteInstance {},
	q1: class extends self.ITextInstance {},
	o1: class extends self.ISpriteInstance {},
	n1: class extends self.ISpriteInstance {},
	texto: class extends self.ITextInstance {},
	Text14: class extends self.ITextInstance {},
	textn: class extends self.ITextInstance {},
	Sprite40: class extends self.ISpriteInstance {},
	x6: class extends self.ISpriteInstance {},
	a1: class extends self.ITextInstance {},
	Text16: class extends self.ITextInstance {},
	moneyword: class extends self.ITextInstance {},
	n2: class extends self.ISpriteInstance {},
	o2: class extends self.ISpriteInstance {},
	p2: class extends self.ISpriteInstance {},
	Sprite34: class extends self.ISpriteInstance {},
	Sprite38: class extends self.ISpriteInstance {},
	boyangry: class extends self.ISpriteInstance {},
	boynogood: class extends self.ISpriteInstance {},
	friendwow: class extends self.ISpriteInstance {},
	friendteach3: class extends self.ISpriteInstance {},
	friendteach: class extends self.ISpriteInstance {},
	highway: class extends self.ISpriteInstance {},
	railway: class extends self.ISpriteInstance {},
	LightRail: class extends self.ISpriteInstance {},
	boydoubt: class extends self.ISpriteInstance {},
	boycry: class extends self.ISpriteInstance {},
	x7: class extends self.ISpriteInstance {},
	angry: class extends self.ISpriteInstance {},
	Sprite39: class extends self.ISpriteInstance {},
	boyexbassred: class extends self.ISpriteInstance {},
	Sprite42: class extends self.ISpriteInstance {},
	aunt: class extends self.ISpriteInstance {},
	Sprite41: class extends self.ISpriteInstance {},
	c1: class extends self.ISpriteInstance {},
	c2: class extends self.ISpriteInstance {},
	Text12: class extends self.ITextInstance {},
	Text13: class extends self.ITextInstance {},
	friendteach2: class extends self.ISpriteInstance {},
	bc: class extends self.ISpriteInstance {},
	gb: class extends self.ISpriteInstance {},
	mc2: class extends self.ISpriteInstance {},
	mc1: class extends self.ISpriteInstance {},
	stone: class extends self.ISpriteInstance {},
	bc5: class extends self.ISpriteInstance {},
	Umbrella: class extends self.ISpriteInstance {},
	Sprite45: class extends self.ISpriteInstance {},
	Text15: class extends self.ITextInstance {},
	按鈕: class extends self.IButtonInstance {},
	Text17: class extends self.ITextInstance {},
	Sprite46: class extends self.ISpriteInstance {},
	start2: class extends self.ISpriteInstance {},
	bluecar: class extends self.ISpriteInstance {},
	鍵盤: class extends self.IInstance {},
	WORD: class extends self.ITextInstance {},
	Sprite48: class extends self.ISpriteInstance {},
	Sprite49: class extends self.ISpriteInstance {},
	car: class extends self.ISpriteInstance {},
	light: class extends self.ISpriteInstance {},
	gutterCover: class extends self.ISpriteInstance {},
	qa: class extends self.ISpriteInstance {},
	Sprite50: class extends self.ISpriteInstance {},
	Text18: class extends self.ITextInstance {},
	Text19: class extends self.ITextInstance {},
	Sprite22: class extends self.ISpriteInstance {},
	Umbrella2: class extends self.ISpriteInstance {},
	bc6: class extends self.ISpriteInstance {},
	Sprite44: class extends self.ISpriteInstance {},
	chair1: class extends self.ISpriteInstance {},
	mc4: class extends self.ISpriteInstance {},
	sc: class extends self.ITextInstance {},
	video2: class extends self.IWorldInstance {},
	skip: class extends self.ITextInstance {},
	ook: class extends self.IButtonInstance {},
	settingword5: class extends self.ITextInstance {},
	settingword6: class extends self.ITextInstance {},
	settingword7: class extends self.ITextInstance {},
	moneyfly: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Sprite16: class extends self.ISpriteInstance {},
	skip3: class extends self.ITextInstance {},
	Sprite17: class extends self.ISpriteInstance {},
	b3: class extends self.ISpriteInstance {},
	b4: class extends self.ISpriteInstance {},
	block1: class extends self.ISpriteInstance {},
	dialogBox5: class extends self.ISpriteInstance {},
	Text20: class extends self.ITextInstance {},
	next: class extends self.ISpriteInstance {},
	Sprite19: class extends self.ISpriteInstance {},
	last: class extends self.ISpriteInstance {},
	next2: class extends self.ISpriteInstance {},
	Sprite43: class extends self.ISpriteInstance {},
	Sprite51: class extends self.ISpriteInstance {},
	back3: class extends self.ISpriteInstance {},
	again: class extends self.ISpriteInstance {},
	next3: class extends self.ISpriteInstance {},
	A11: class extends self.ISpriteInstance {},
	A22: class extends self.ISpriteInstance {},
	A33: class extends self.ISpriteInstance {},
	A44: class extends self.ISpriteInstance {},
	A55: class extends self.ISpriteInstance {},
	B11: class extends self.ISpriteInstance {},
	B22: class extends self.ISpriteInstance {},
	B33: class extends self.ISpriteInstance {},
	B44: class extends self.ISpriteInstance {},
	B55: class extends self.ISpriteInstance {},
	C11: class extends self.ISpriteInstance {},
	C22: class extends self.ISpriteInstance {},
	C33: class extends self.ISpriteInstance {},
	C44: class extends self.ISpriteInstance {},
	C55: class extends self.ISpriteInstance {},
	D11: class extends self.ISpriteInstance {},
	D22: class extends self.ISpriteInstance {},
	D33: class extends self.ISpriteInstance {},
	D44: class extends self.ISpriteInstance {},
	D55: class extends self.ISpriteInstance {},
	E11: class extends self.ISpriteInstance {},
	E22: class extends self.ISpriteInstance {},
	E33: class extends self.ISpriteInstance {},
	E44: class extends self.ISpriteInstance {},
	E55: class extends self.ISpriteInstance {},
	r4: class extends self.ISpriteInstance {},
	r41: class extends self.ISpriteInstance {},
	r5: class extends self.ISpriteInstance {},
	r51: class extends self.ISpriteInstance {},
	r6: class extends self.ISpriteInstance {},
	r61: class extends self.ISpriteInstance {},
	r7: class extends self.ISpriteInstance {},
	r71: class extends self.ISpriteInstance {},
	girl1: class extends self.ISpriteInstance {},
	girl2: class extends self.ISpriteInstance {},
	Text21: class extends self.ITextInstance {},
	girl3: class extends self.ISpriteInstance {},
	vedio21: class extends self.IWorldInstance {},
	x8: class extends self.ISpriteInstance {},
	preservation1: class extends self.ISpriteInstance {},
	preservation2: class extends self.ISpriteInstance {},
	vedio22: class extends self.IWorldInstance {},
	x9: class extends self.ISpriteInstance {},
	vedio23: class extends self.IWorldInstance {},
	back5: class extends self.ISpriteInstance {},
	vedio24: class extends self.IWorldInstance {},
	x10: class extends self.ISpriteInstance {},
	Text22: class extends self.ITextInstance {},
	Text23: class extends self.ITextInstance {},
	giel4: class extends self.ISpriteInstance {},
	sc1: class extends self.ISpriteInstance {},
	bc8: class extends self.ISpriteInstance {},
	vedio25: class extends self.IWorldInstance {},
	x11: class extends self.ISpriteInstance {},
	Text24: class extends self.ITextInstance {},
	bc7: class extends self.ISpriteInstance {},
	stopline1: class extends self.ISpriteInstance {},
	Sprite18: class extends self.ISpriteInstance {},
	Text25: class extends self.ITextInstance {},
	talk2: class extends self.ISpriteInstance {},
	talk3: class extends self.ISpriteInstance {},
	talk4: class extends self.ISpriteInstance {},
	map: class extends self.ISpriteInstance {},
	stopline2: class extends self.ISpriteInstance {},
	stopline3: class extends self.ISpriteInstance {},
	stopline4: class extends self.ISpriteInstance {},
	x12: class extends self.ISpriteInstance {},
	back6: class extends self.ISpriteInstance {},
	start5: class extends self.ISpriteInstance {},
	bc10: class extends self.ISpriteInstance {},
	U11: class extends self.IWorldInstance {},
	U12: class extends self.IWorldInstance {},
	U14: class extends self.IWorldInstance {},
	U15: class extends self.IWorldInstance {},
	skip55: class extends self.ISpriteInstance {},
	Text26: class extends self.ITextInstance {},
	ed: class extends self.ITextInstance {},
	yellow: class extends self.ISpriteInstance {},
	Sprite20: class extends self.ISpriteInstance {},
	U224: class extends self.IWorldInstance {},
	U31: class extends self.IWorldInstance {},
	U32: class extends self.IWorldInstance {},
	map2: class extends self.ISpriteInstance {},
	music2: class extends self.ISpriteInstance {},
	moal: class extends self.ISpriteInstance {},
	right2: class extends self.ISpriteInstance {},
	left2: class extends self.ISpriteInstance {},
	right3: class extends self.ISpriteInstance {},
	left3: class extends self.ISpriteInstance {},
	settingmoal: class extends self.ISpriteInstance {},
	x13: class extends self.ISpriteInstance {},
	setting3: class extends self.ISpriteInstance {},
	aa1: class extends self.ISpriteInstance {},
	aa2: class extends self.ISpriteInstance {},
	sale: class extends self.ISpriteInstance {},
	piece1: class extends self.ISpriteInstance {},
	piece2: class extends self.ISpriteInstance {},
	piece3: class extends self.ISpriteInstance {},
	piece4: class extends self.ISpriteInstance {},
	lamp: class extends self.ISpriteInstance {},
	chair2: class extends self.ISpriteInstance {},
	chair3: class extends self.ISpriteInstance {},
	chair4: class extends self.ISpriteInstance {},
	chair5: class extends self.ISpriteInstance {},
	aa3: class extends self.ISpriteInstance {},
	bc12: class extends self.ISpriteInstance {},
	carrrrr1: class extends self.ISpriteInstance {},
	carrrrrr2: class extends self.ISpriteInstance {},
	gutterCover2: class extends self.ISpriteInstance {},
	glass: class extends self.ISpriteInstance {},
	aa4: class extends self.ISpriteInstance {},
	U2setting: class extends self.ISpriteInstance {},
	ok1: class extends self.ISpriteInstance {},
	settingmeal2: class extends self.ISpriteInstance {},
	Obstruct1: class extends self.ISpriteInstance {},
	Obstruct2: class extends self.ISpriteInstance {},
	Obstruct3: class extends self.ISpriteInstance {},
	Obstruct4: class extends self.ISpriteInstance {},
	Obstruct5: class extends self.ISpriteInstance {},
	bc13: class extends self.ISpriteInstance {},
	car5: class extends self.ISpriteInstance {},
	mc5: class extends self.ISpriteInstance {},
	bc14: class extends self.ISpriteInstance {},
	people: class extends self.ISpriteInstance {},
	venders: class extends self.ISpriteInstance {},
	plant2: class extends self.ISpriteInstance {},
	wash: class extends self.ISpriteInstance {},
	play: class extends self.ISpriteInstance {},
	x14: class extends self.ISpriteInstance {},
	bc15: class extends self.ISpriteInstance {},
	play2: class extends self.ISpriteInstance {},
	x15: class extends self.ISpriteInstance {},
	rr1: class extends self.ISpriteInstance {},
	rr2: class extends self.ISpriteInstance {},
	rr3: class extends self.ISpriteInstance {},
	rr4: class extends self.ISpriteInstance {},
	rr11: class extends self.ISpriteInstance {},
	rr44: class extends self.ISpriteInstance {},
	rr22: class extends self.ISpriteInstance {},
	rr33: class extends self.ISpriteInstance {},
	u25sertting: class extends self.ISpriteInstance {},
	circle: class extends self.ISpriteInstance {},
	line1: class extends self.ISpriteInstance {},
	line2: class extends self.ISpriteInstance {},
	line3: class extends self.ISpriteInstance {},
	line4: class extends self.ISpriteInstance {},
	circle2: class extends self.ISpriteInstance {},
	line6: class extends self.ISpriteInstance {},
	line7: class extends self.ISpriteInstance {},
	line8: class extends self.ISpriteInstance {},
	line9: class extends self.ISpriteInstance {},
	line10: class extends self.ISpriteInstance {},
	line11: class extends self.ISpriteInstance {},
	line12: class extends self.ISpriteInstance {},
	line13: class extends self.ISpriteInstance {},
	line14: class extends self.ISpriteInstance {},
	line16: class extends self.ISpriteInstance {},
	line17: class extends self.ISpriteInstance {},
	line18: class extends self.ISpriteInstance {},
	line19: class extends self.ISpriteInstance {},
	line20: class extends self.ISpriteInstance {},
	line21: class extends self.ISpriteInstance {},
	line22: class extends self.ISpriteInstance {},
	redcar: class extends self.ISpriteInstance {},
	aa5: class extends self.ISpriteInstance {},
	aa6: class extends self.ISpriteInstance {},
	next5: class extends self.ISpriteInstance {},
	next6: class extends self.ISpriteInstance {},
	U30: class extends self.IWorldInstance {},
	U40: class extends self.IWorldInstance {},
	U41: class extends self.IWorldInstance {},
	Text27: class extends self.ITextInstance {},
	boyknow: class extends self.ISpriteInstance {},
	Text28: class extends self.ITextInstance {},
	Sprite12: class extends self.ISpriteInstance {},
	com: class extends self.ISpriteInstance {},
	read: class extends self.ISpriteInstance {},
	fb1: class extends self.ISpriteInstance {},
	car01: class extends self.ISpriteInstance {},
	car001: class extends self.ISpriteInstance {},
	Sprite52: class extends self.ISpriteInstance {},
	Sprite53: class extends self.ISpriteInstance {},
	Sprite54: class extends self.ISpriteInstance {},
	Sprite55: class extends self.ISpriteInstance {},
	Browser: class extends self.IInstance {},
	fb0: class extends self.ISpriteInstance {},
	fb2: class extends self.ISpriteInstance {},
	Sprite47: class extends self.ISpriteInstance {},
	fb3: class extends self.ISpriteInstance {},
	Sprite56: class extends self.ISpriteInstance {},
	continue: class extends self.ISpriteInstance {},
	Sprite57: class extends self.ISpriteInstance {},
	Sprite58: class extends self.ISpriteInstance {},
	Sprite59: class extends self.ISpriteInstance {},
	Sprite60: class extends self.ISpriteInstance {}
}